name: iswot
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  #- _x86_64-microarch-level=3=2_skylake #problematic
  - affine=2.4.0=pyhd8ed1ab_1
  - aiobotocore=2.23.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.13=py313h8060acc_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py313h536fd9c_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=hbfa7f16_15
  - aws-c-cal=0.9.2=h5e3027f_0
  - aws-c-common=0.12.3=hb9d3cd8_0
  - aws-c-compression=0.3.1=hafb2847_5
  - aws-c-event-stream=0.5.4=h76f0014_12
  - aws-c-http=0.10.2=h015de20_2
  - aws-c-io=0.20.1=hdfce8c9_0
  - aws-c-mqtt=0.13.1=h1e5e6c0_3
  - aws-c-s3=0.8.3=h5e174a9_0
  - aws-c-sdkutils=0.2.4=hafb2847_0
  - aws-checksums=0.2.7=hafb2847_1
  - aws-crt-cpp=0.32.10=hff780f1_1
  - aws-sdk-cpp=1.11.510=h937e755_12
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backoff=2.2.1=pyhd8ed1ab_1
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.7.3=pyhd8ed1ab_0
  - botocore=1.38.27=pyge310_1234567_0
  - bounded-pool-executor=0.0.3=pyhd8ed1ab_0
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py313h46c70d0_3
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - capnproto=1.2.0=hfc315d8_0
  - cartopy=0.24.0=py313ha87cce1_0
  - cattrs=24.1.2=py313h06a4308_0
  - ceres-solver=2.2.0=cpuh39c81a5_6
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - cftime=1.6.4=py313ha014f3b_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - cmocean=4.0.3=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorcet=3.1.0=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h33d0bda_0
  - cpd=0.5.5=h434a139_2
  - crc32c=2.7.1=py313h536fd9c_1
  - curlify=2.2.1=pyh44b312d_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dask-core=2024.12.1=pyhd8ed1ab_0
  - dask-expr=1.1.21=pyhd8ed1ab_0
  - datashader=0.18.1=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.14=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - dnspython=2.7.0=pyhff2d567_1
  - docopt-ng=0.9.0=pyhd8ed1ab_1
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - draco=1.5.7=h00ab1b0_0
  - earthaccess=0.12.0=pyhd8ed1ab_1
  - eigen=3.4.0=hdb19cb5_0
  - email-validator=2.2.0=pyhd8ed1ab_1
  - email_validator=2.2.0=hd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - fastapi=0.116.1=h26c32bb_1
  - fastapi-cli=0.0.8=pyhd8ed1ab_0
  - fastapi-core=0.116.1=pyhe01879c_1
  - fasteners=0.19=pyhd8ed1ab_1
  - fgt=0.4.11=h87365c0_1
  - fiona=1.10.1=py313hab4ff3b_3
  - fmt=11.2.0=h07f6e7f_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py313h8060acc_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=ha770c72_1
  - freexl=2.0.0=h9dce30a_2
  - frozenlist=1.6.0=py313h61b7b33_0
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - geojson=3.2.0=pyhd8ed1ab_0
  - geomet=1.1.0=pyhd8ed1ab_0
  - geopandas=1.1.1=pyhd8ed1ab_0
  - geopandas-base=1.1.1=pyha770c72_0
  - geos=3.13.1=h97f6797_0
  - geotiff=1.7.4=h239500f_2
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - graphite2=1.3.14=h5888daf_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5netcdf=1.6.3=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py313hfaf8fd4_100
  - harfbuzz=11.2.1=h3beb420_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h2d575fe_101
  - holoviews=1.21.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - html2text=2025.4.15=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.6.4=py313h536fd9c_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hvplot=0.11.3=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icepyx=2.0.0=pyhe01879c_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.3.0=pyhfa0c392_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=7.8.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=py313h06a4308_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py313h78bf25f_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.24.0=hd8ed1ab_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhe01879c_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=1.1.11=pyhd8ed1ab_0
  - kerchunk=0.2.7=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py313h33d0bda_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.4=h3f801dc_0
  - libamd=3.3.3=haaf9dc3_7100102
  - libarchive=3.8.1=gpl_h98cc613_100
  - libarrow=20.0.0=h1b9301b_8_cpu
  - libarrow-acero=20.0.0=hcb10f89_8_cpu
  - libarrow-dataset=20.0.0=hcb10f89_8_cpu
  - libarrow-substrait=20.0.0=h1bed206_8_cpu
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libbtf=2.3.2=h32481e8_7100102
  - libcamd=3.3.3=h32481e8_7100102
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=32_he106b2a_openblas
  - libccolamd=3.3.4=h32481e8_7100102
  - libcholmod=5.3.1=h59ddab4_7100102
  - libclang-cpp20.1=20.1.7=default_h1df26ce_0
  - libclang13=20.1.7=default_he06ed0a_0
  - libcolamd=3.3.4=h32481e8_7100102
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libcxsparse=4.4.1=h32481e8_7100102
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libfabric=2.2.0=ha770c72_0
  - libfabric1=2.2.0=hf45584d_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgdal-arrow-parquet=3.10.3=h8169c6c_11
  - libgdal-core=3.10.3=hcac4edf_11
  - libgdal-hdf5=3.10.3=hc4e49b7_11
  - libgdal-pg=3.10.3=hfb06ed7_11
  - libgdal-postgisraster=3.10.3=hfb06ed7_11
  - libgdal-tiledb=3.10.3=hd16f1d8_11
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.71.0=h8e591d7_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libklu=2.3.5=hf24d653_7100102
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - libldl=3.3.2=h32481e8_7100102
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnetcdf=4.9.2=nompi_h0134ee8_117
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_0
  - libparquet=20.0.0=h081d1f1_8_cpu
  - libparu=1.0.0=h17147ab_7100102
  - libpciaccess=0.18=hb9d3cd8_0
  - libpdal=2.8.4=h453e6b4_6
  - libpdal-arrow=2.8.4=hb7ef14c_6
  - libpdal-core=2.8.4=h921c622_6
  - libpdal-cpd=2.8.4=hbb46d0d_6
  - libpdal-draco=2.8.4=hbb46d0d_6
  - libpdal-e57=2.8.4=h0dda180_6
  - libpdal-hdf=2.8.4=haa54232_6
  - libpdal-icebridge=2.8.4=haa54232_6
  - libpdal-nitf=2.8.4=h986040f_6
  - libpdal-pgpointcloud=2.8.4=h5c7ba8f_6
  - libpdal-tiledb=2.8.4=h68be023_6
  - libpdal-trajectory=2.8.4=hb16f371_6
  - libpmix=5.0.8=h658e747_0
  - libpng=1.6.49=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=5.29.3=h501fc15_1
  - librbio=4.3.4=h32481e8_7100102
  - libre2-11=2025.06.26=hba17884_0
  - librttopo=1.1.0=hd718a1a_18
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=he17ca71_14
  - libspex=3.2.3=had10066_7100102
  - libspqr=4.3.4=h852d39f_7100102
  - libsqlite=3.50.2=h6cd9bfd_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsuitesparseconfig=7.10.1=h92d6892_7100102
  - libsystemd0=257.7=h4e0b6ca_0
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hf01ce69_5
  - libudev1=257.7=hbe16f8c_0
  - libumfpack=6.3.5=heb53515_7100102
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - llvmlite=0.44.0=py313h1b76d92_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=6.0.0=py313h73548e6_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mapclassify=2.9.0=pyhd8ed1ab_0
  - markdown=3.8.2=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py313h8060acc_1
  - matplotlib=3.10.3=py313h78bf25f_0
  - matplotlib-base=3.10.3=py313h129903b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdit-py-plugins=0.4.2=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - metis=5.1.0=hf484d3e_4
  - minizip=4.0.10=h05a5f5f_0
  - mistune=3.1.3=pyh29332c3_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0=openmpi
  - msgpack-python=1.1.1=py313h33d0bda_0
  - multidict=6.6.3=py313h8060acc_0
  - multimethod=2.0=pyhd8ed1ab_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - narwhals=1.45.0=pyhe01879c_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py313h6d1955d_102
  - networkx=3.5=pyhe01879c_0
  - nitro=2.7.dev8=h59595ed_0
  - nlohmann_json=3.12.0=h3f2d84a_0
  - notebook=7.4.4=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.61.2=py313h50b8c88_1
  - numcodecs=0.15.1=py313ha87cce1_0
  - numpy=2.2.6=py313h17eae1a_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openmpi=5.0.8=h41ff47f_100
  - openssl=3.5.1=h7b32b05_0
  - orc=2.1.2=h17f744e_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - pandas=2.3.0=py313ha87cce1_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.7.2=pyhd8ed1ab_0
  - param=2.2.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.45=hc749103_0
  - pdal=2.8.4=hd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py313h8db990d_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - pockets=0.9.1=pyhd8ed1ab_1
  - postgresql=17.5=h607a889_0
  - pqdm=0.2.0=pyhd8ed1ab_1
  - progressbar2=4.2.0=pyhd8ed1ab_0
  - proj=9.6.2=h0054346_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - propcache=0.3.1=py313h8060acc_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=20.0.0=py313h78bf25f_0
  - pyarrow-core=20.0.0=py313he5f92c8_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pyct=0.5.0=pyhd8ed1ab_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py313h4b2b08d_0
  - pydap=3.5.5=pyhecae5ae_0
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.11.0=py313hab4ff3b_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.7.1=py313hcd509b5_1
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pyside6=6.9.0=py313h5f61773_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.5=hec9711d_102_cp313
  - python-cmr=0.13.0=pyhff2d567_1
  - python-dotenv=0.20.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-pdal=3.4.5=py313h61d996b_14
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-utils=3.9.1=pyhff2d567_1
  - python_abi=3.13=7_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyviz_comms=3.0.6=pyhd8ed1ab_0
  - pyyaml=6.0.2=py313h8060acc_2
  - pyzmq=27.0.0=py313h8e95178_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h0384650_3
  - rasterio=1.4.3=py313h3209d2e_1
  - rdma-core=57.0=h5888daf_0
  - re2=2025.06.26=h9925aae_0
  - readline=8.2=h5eee18b_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=pyhd8ed1ab_0
  - requests-cache=1.2.0=py313h06a4308_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=14.1.0=pyhe01879c_0
  - rich-toolkit=0.14.9=pyhe01879c_0
  - rioxarray=0.19.0=pyhd8ed1ab_0
  - rpds-py=0.25.1=py313h4b2b08d_0
  - s2n=1.5.21=h7ab7c64_0
  - s3fs=2025.5.1=pyhd8ed1ab_0
  - scikit-learn=1.7.0=py313h8ef605b_1
  - scipy=1.16.0=py313h86fcf2b_0
  - send2trash=1.8.3=pyh0d859eb_1
  - sentinelsat=1.2.1=pyhd8ed1ab_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.0.7=py313h576e190_1
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - soupsieve=2.7=pyhd8ed1ab_0
  - spdlog=1.15.3=h6dc744f_1
  - sphinxcontrib-napoleon=0.7=pyhd8ed1ab_1
  - sqlite=3.50.2=hb7a22d2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.47.2=pyh82d4cca_0
  - suitesparse=7.10.1=ha0f6916_7100102
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - threddsclient=0.4.6=pyhd8ed1ab_1
  - tiledb=2.28.0=hccce5bd_6
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tinynetrc=1.3.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.1=py313h536fd9c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.16.0=pyh167b9f4_0
  - typer-slim=0.16.0=pyhe01879c_0
  - typer-slim-standard=0.16.0=hf964461_0
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzcode=2025b=hb9d3cd8_0
  - tzdata=2025b=h04d1e81_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - ucc=1.4.4=h2b97398_0
  - ucx=1.18.1=h1369271_0
  - ujson=5.10.0=py313h46c70d0_1
  - unicodedata2=16.0.0=py313h536fd9c_0
  - universal_pathlib=0.2.6=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=hac33072_0
  - url-normalize=1.4.3=py313h06a4308_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uvicorn=0.35.0=pyh31011fe_0
  - uvicorn-standard=0.35.0=h31011fe_0
  - uvloop=0.21.0=py313h536fd9c_1
  - virtualizarr=1.2.0=pyhd8ed1ab_0
  - watchfiles=1.1.0=py313h920b4c0_0
  - wayland=1.23.1=h3e06ad9_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - webob=1.8.7=pyhd3eb1b0_0
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - websockets=15.0.1=py313h536fd9c_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=3.6.10=pyhd8ed1ab_0
  - wrapt=1.17.2=py313h536fd9c_0
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=h988505b_2
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.1=py313h8060acc_0
  - zarr=3.1.0=pyhe01879c_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - harmony-py==0.4.15
      - packaging==23.2
      - pdal-plugins==1.6.2
      - podaac-data-subscriber==1.15.2
      - python-dateutil==2.8.2
      - tenacity==8.5.0
prefix: /home/framo4051/anaconda3/envs/iswot
